version: '3'

services:
  go:
    image: golang:1.15
    command: sh -c "go test -v ; go get golang.org/x/tools/cmd/godoc && godoc -http=:6060"
    working_dir: /app/speedtester
    volumes:
      - ./:/app
    environment:
      - CGO_ENABLED=0
    ports:
      - 6060:6060
